# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50bd202ea2f45aecd2fe69b0b9d6aa7b8b69c23ad9dc37c922108e99adf4f296e4612bad123d480c02d47c2f75952abb6bfa7d81bfa24c4111074d7fbfbff80f

test:
  secret_key_base: e427197ff05c5b0217bbf1ebb4bb521354975e7cf6b87485c7445c17ef41f3b560800ec89600621055624c69a9adf23516cf36670b148f5779783dea1c64ad98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
